# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d63ded579dc609678d7d1edc2b0df3a2de3dcbf000f98f7bab269e00821b8a4dc843136125f68bc1b37393dff649c70b31dfe67b87badde23e9506758542312

test:
  secret_key_base: d2ed604f1ae151f9b2dd37efe28a080a8eceb1ee1ffb49451f09969ed778d37b4c4835fe74210da94bda1bc9ee03c077c45a00878f0f9c5ef57c8dd35f12abd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
